# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false

before_script:
  - while sleep 30; do tail ~/build/ppalmes/TSMLextra.jl/deps/build.log -f ; done &

before_install:
  # linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y "deb http://cran.rstudio.com/bin/linux/ubuntu $(lsb_release -s -c)/"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq -y; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install git r-base r-base-dev r-recommended -y; fi
  #- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install r-cran-caret r-cran-randomforest r-cran-mass r-cran-e1071 r-cran-gam -y; fi
  #- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install r-cran-kernlab r-cran-nnet r-cran-grid r-cran-pls -y; fi


  # osx
  # faster than using homebrew/science tap
  # but no permalink to release download
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then wget "https://cran.rstudio.com/bin/macosx/$(wget -qO- https://cran.rstudio.com/bin/macosx/ | sed -n 's/.*href="\(R-[^"]*.pkg\)".*/\1/p' | head -n 1)"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo installer -pkg R-*.pkg -target /; fi

after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      julia --project=coverage/ -e 'using Pkg; Pkg.instantiate();
      using Coverage; Codecov.submit(Codecov.process_folder())';
    fi



#jobs:
#  include:
#    - stage: "Documentation"
#      julia: 1.0
#      os: osx
#      script:
#        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
#        - julia --project=docs/ docs/make.jl
#      name: "HTML"
#      after_success: skip
#    - script:
#        - julia --project=docs/pdf/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
#        - julia --project=docs/pdf/ docs/pdf/make.jl
#      name: "PDF"
#      after_success: skip
#      services: docker
